<?php 

return [
    [
        'name' => 'Niall Horan: "The Show" Live',
        'date' => '2025-05-13',
        'time' => '7:30PM - 10:00PM',
        'venue' => 'Mall Of Asia Arena',
        'address' => 'Pasay',
        'description' => 'Catch Niall Horan live as he performs his greatest hits from his latest album "The Show" and more! Experience an unforgettable night of music with one of pop\'s biggest stars. The former One Direction member brings his solo tour to Manila for the first time, showcasing his musical evolution and chart-topping songs.',
        'longitude' => 120.9841,
        'latitude' => 14.5344,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'BINIverse',
        'date' => '2025-03-28',
        'time' => '6:00PM - 9:00PM',
        'venue' => 'New Frontier Theater',
        'address' => 'Cubao',
        'description' => 'Join BINI, the Nation\'s Girl Group, for an exciting concert experience! BINI Universe showcases the group\'s talent, charisma, and hit songs in an immersive show designed for their fans. Get ready for stunning performances, beautiful vocals, and powerful choreography that will leave you breathless.',
        'longitude' => 121.0529,
        'latitude' => 14.6217,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Taylor Swift: The Eras Tour',
        'date' => '2025-04-03',
        'time' => '6:00PM - 11:00PM',
        'venue' => 'Philippine Arena',
        'address' => 'Bulacan',
        'description' => 'The most anticipated concert event of the year! Taylor Swift brings her record-breaking Eras Tour to the Philippines for the first time. Join thousands of Swifties for this once-in-a-lifetime concert experience spanning all eras of Taylor\'s illustrious career. Featuring hit songs from all her albums, stunning visuals, and unforgettable performances.',
        'longitude' => 120.9481,
        'latitude' => 14.7631,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Coldplay: Music of the Spheres',
        'date' => '2025-06-19',
        'time' => '7:00PM - 10:30PM',
        'venue' => 'Philippine Arena',
        'address' => 'Bulacan',
        'description' => 'Coldplay returns to the Philippines with their spectacular Music of the Spheres World Tour! Experience the band\'s acclaimed live show featuring stunning visuals, interactive light displays, and all their greatest hits. The eco-friendly concert showcases Coldplay\'s commitment to sustainability while delivering an unforgettable musical journey.',
        'longitude' => 120.9481,
        'latitude' => 14.7631,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Eraserheads Reunion',
        'date' => '2025-04-25',
        'time' => '7:00PM - 11:00PM',
        'venue' => 'Rizal Park',
        'address' => 'Manila',
        'description' => 'The legendary Eraserheads reunite for a special concert under the stars at Rizal Park. Witness Philippine rock history as Ely, Marcus, Buddy, and Raymund perform their iconic hits that defined a generation. From "Ang Huling El Bimbo" to "Alapaap," relive the magic of the band\'s extensive catalog in this must-see event.',
        'longitude' => 120.9794,
        'latitude' => 14.5831,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Ben&Ben Live',
        'date' => '2025-04-05',
        'time' => '6:30PM - 9:30PM',
        'venue' => 'BGC Amphitheater',
        'address' => 'Taguig',
        'description' => 'Experience the heartfelt music of Ben&Ben in an intimate outdoor setting. The 9-piece folk-pop band will perform their hit songs along with new material from their latest album. Known for their poetic lyrics and unique instrumentation, this concert promises an evening of musical connection and emotional depth.',
        'longitude' => 121.0500,
        'latitude' => 14.5478,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'FIBA Asia 2025 Qualifiers',
        'date' => '2025-03-22',
        'time' => '7:00PM - 9:00PM',
        'venue' => 'Mall Of Asia Arena',
        'address' => 'Pasay',
        'description' => 'Cheer on the Philippines as they face tough competition in the FIBA Asia 2025 Qualifiers. Witness international basketball at its finest as our national team competes for a spot in the prestigious FIBA Asia Cup. The qualifying match features our country\'s best players showing their skills and national pride.',
        'longitude' => 120.9841,
        'latitude' => 14.5344,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'PVL 2025',
        'date' => '2025-05-03',
        'time' => '2:00PM - 6:00PM',
        'venue' => 'Smart Araneta',
        'address' => 'Cubao',
        'description' => 'Watch the Premier Volleyball League (PVL) as the top volleyball teams in the Philippines compete for championship glory. This match features exciting rallies, powerful spikes, and amazing defensive plays. Support your favorite teams and players in this thrilling display of volleyball excellence.',
        'longitude' => 121.0514,
        'latitude' => 14.6197,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'PBA All Star Game',
        'date' => '2025-04-12',
        'time' => '5:00PM - 8:00PM',
        'venue' => 'Smart Araneta',
        'address' => 'Cubao',
        'description' => 'The PBA All-Star Game brings together the brightest stars of Philippine Basketball for an exhibition of skill, entertainment, and friendly competition. Featuring skills challenges, a three-point shootout, slam dunk contest, and the main All-Star Game, this is basketball entertainment at its finest for fans of all ages.',
        'longitude' => 121.0514,
        'latitude' => 14.6197,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'UAAP Volleyball Finals',
        'date' => '2025-05-18',
        'time' => '3:00PM - 7:00PM',
        'venue' => 'Mall Of Asia Arena',
        'address' => 'Pasay',
        'description' => 'Experience the intensity of the UAAP Volleyball Finals as the top university teams battle for the championship. The culmination of months of competition, this match promises thrilling exchanges, school spirit, and elite collegiate volleyball action. Support your alma mater or favorite university in this exciting sports event.',
        'longitude' => 120.9841,
        'latitude' => 14.5344,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Disney on Ice',
        'date' => '2025-06-25',
        'time' => '1:00PM - 3:00PM, 6:00PM - 8:00PM',
        'venue' => 'Smart Araneta',
        'address' => 'Cubao',
        'description' => 'Disney On Ice presents magical ice skating performances featuring beloved Disney characters. Watch as skilled skaters bring your favorite Disney stories to life through stunning choreography, colorful costumes, and memorable music. An enchanting experience for Disney fans of all ages that creates lasting family memories.',
        'longitude' => 121.0514,
        'latitude' => 14.6197,
        'category' => 'KIDS'
    ],
    [
        'name' => 'Kidzoona Play Festival',
        'date' => '2025-07-15',
        'time' => '10:00AM - 8:00PM',
        'venue' => 'SMX Convention',
        'address' => 'Pasay',
        'description' => 'The Kidzoona Play Festival transforms SMX Convention Center into the ultimate children\'s playground. With inflatable attractions, ball pits, interactive games, and creative zones, kids can play, explore, and have fun in a safe environment. Special appearances by children\'s characters and entertaining shows throughout the day make this a complete family event.',
        'longitude' => 120.9866,
        'latitude' => 14.5362,
        'category' => 'KIDS'
    ],
    [
        'name' => 'Philippine Philharmonic Orchestra',
        'date' => '2025-03-28',
        'time' => '8:00PM - 10:00PM',
        'venue' => 'Cultural Center',
        'address' => 'Manila',
        'description' => 'Experience the musical excellence of the Philippine Philharmonic Orchestra in this special concert featuring both classical masterpieces and Filipino compositions. Under the baton of their acclaimed conductor, the orchestra delivers a program that showcases technical brilliance and emotional depth. An evening of orchestral beauty in the iconic Cultural Center of the Philippines.',
        'longitude' => 120.9796,
        'latitude' => 14.5565,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Art in the Park 2025',
        'date' => '2025-04-20',
        'time' => '10:00AM - 10:00PM',
        'venue' => 'Jaime Velasquez Park',
        'address' => 'Makati',
        'description' => 'Art in the Park transforms Jaime Velasquez Park into an outdoor art gallery featuring affordable artworks from leading and emerging Filipino artists. Browse paintings, sculptures, prints, and mixed media pieces in a relaxed park setting. With live music, food stalls, and interactive art activities, this annual event makes art accessible to everyone while supporting the local art community.',
        'longitude' => 121.0297,
        'latitude' => 14.5550,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Manila Food Festival',
        'date' => '2025-03-25',
        'time' => '11:00AM - 10:00PM',
        'venue' => 'Bonifacio High Street',
        'address' => 'BGC',
        'description' => 'Savor the diverse flavors of the Philippines at the Manila Food Festival. This culinary celebration features food stalls from the country\'s best restaurants, street food vendors, and innovative chefs. Sample regional specialties, trendy fusion dishes, and classic Filipino favorites while enjoying cooking demonstrations, food competitions, and live entertainment throughout the day.',
        'longitude' => 121.0551,
        'latitude' => 14.5509,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Summer Music Festival',
        'date' => '2025-05-10',
        'time' => '3:00PM - 1:00AM',
        'venue' => 'Clark Global City Park',
        'address' => 'Pampanga',
        'description' => 'The Summer Music Festival brings together top artists from multiple genres for a day-long celebration of music under the stars. With multiple stages, food concessions, art installations, and camping options, this festival offers a complete experience for music lovers. The lineup features both international acts and homegrown Filipino talent in a picturesque outdoor setting.',
        'longitude' => 120.5562,
        'latitude' => 15.1868,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Street Food Night Market',
        'date' => '2025-03-20',
        'time' => '5:00PM - 12:00AM',
        'venue' => 'Circuit Makati',
        'address' => 'Makati',
        'description' => 'Experience the vibrant street food culture of the Philippines at this lively night market. Dozens of vendors offer everything from classic Filipino street fare to international snacks with local twists. The market features atmospheric lighting, live acoustic performances, and communal dining areas, creating a festive social environment perfect for foodies and night owls.',
        'longitude' => 121.0153,
        'latitude' => 14.5652,
        'category' => 'ARTS'
    ],
    [
        'name' => 'TWICE x ONCE',
        'date' => '2025-04-15',
        'time' => '6:30PM - 9:30PM',
        'venue' => 'Mall Of Asia',
        'address' => 'Pasay',
        'description' => 'TWICE brings their electrifying performance to Manila! The globally acclaimed K-pop girl group will showcase their impressive repertoire of hits in this highly anticipated concert. ONCE (TWICE\'s official fandom) can look forward to spectacular choreography, stunning visuals, and the group\'s signature infectious energy in an unforgettable show that celebrates the special bond between TWICE and their fans.',
        'longitude' => 120.9841,
        'latitude' => 14.5344,
        'category' => 'CONCERT'
    ],
    // Additional events with updated dates
    [
        'name' => 'Blackpink World Tour: Born Pink',
        'date' => '2025-06-18',
        'time' => '7:00PM - 10:30PM',
        'venue' => 'Philippine Arena',
        'address' => 'Bulacan',
        'description' => 'Global K-pop sensation Blackpink returns to Manila with their spectacular Born Pink World Tour. Experience the phenomenal group\'s high-energy performances, stunning choreography, and hit songs that have broken records worldwide. This highly anticipated concert promises state-of-the-art production, incredible visuals, and the charismatic stage presence that has made Blackpink international superstars.',
        'longitude' => 120.9481,
        'latitude' => 14.7631,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Manila International Book Fair',
        'date' => '2025-09-12',
        'time' => '10:00AM - 8:00PM',
        'venue' => 'SMX Convention',
        'address' => 'Pasay',
        'description' => 'The Manila International Book Fair returns for its annual celebration of literature and publishing. Browse thousands of titles from local and international publishers, attend book signings by favorite authors, and participate in engaging literary discussions and workshops. With special sections for children\'s literature, academic books, and digital publishing, this event caters to readers of all ages and interests.',
        'longitude' => 120.9866,
        'latitude' => 14.5362,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Broadway Manila: The Lion King',
        'date' => '2025-07-25',
        'time' => '8:00PM - 10:30PM',
        'venue' => 'Newport Performing Arts Theater',
        'address' => 'Pasay',
        'description' => 'Experience the magic of Disney\'s The Lion King as the acclaimed Broadway production makes its Philippine debut. This spectacular theatrical event brings to life the beloved story through stunning costumes, puppetry, and unforgettable music by Elton John and Tim Rice. The visionary direction and design transform the stage into the African savanna in this award-winning production that has captivated audiences worldwide.',
        'longitude' => 121.0213,
        'latitude' => 14.5172,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Manila Coffee Festival',
        'date' => '2025-04-22',
        'time' => '9:00AM - 6:00PM',
        'venue' => 'World Trade Center',
        'address' => 'Pasay',
        'description' => 'Celebrate the rich coffee culture of the Philippines at the Manila Coffee Festival. This event showcases the finest local coffee producers, from small-batch specialty roasters to traditional coffee farmers from across the archipelago. Enjoy coffee tastings, barista competitions, brewing workshops, and discussions on sustainable coffee production. Discover the unique flavors and stories behind Philippine coffee in this caffeine-fueled celebration.',
        'longitude' => 120.9845,
        'latitude' => 14.5368,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Philippines GameCon 2025',
        'date' => '2025-08-15',
        'time' => '10:00AM - 9:00PM',
        'venue' => 'SMX Convention',
        'address' => 'Pasay',
        'description' => 'Philippines GameCon brings together gamers, developers, and industry professionals for the country\'s premier gaming event. Experience the latest video game releases, esports tournaments with top teams, cosplay competitions, and panel discussions with game creators. With hands-on demo stations, retro gaming areas, and exclusive merchandise, this convention celebrates gaming culture in all its forms.',
        'longitude' => 120.9866,
        'latitude' => 14.5362,
        'category' => 'KIDS'
    ],
    [
        'name' => 'Ballet Philippines: Swan Lake',
        'date' => '2025-05-24',
        'time' => '7:30PM - 10:00PM',
        'venue' => 'Cultural Center',
        'address' => 'Manila',
        'description' => 'Ballet Philippines presents Tchaikovsky\'s masterpiece Swan Lake in a breathtaking production that showcases the company\'s artistic excellence. This timeless ballet tells the story of Prince Siegfried and Odette, a princess turned into a swan by an evil sorcerer\'s curse. With stunning choreography, elaborate costumes, and the iconic score performed by a live orchestra, this production brings classical ballet\'s most beloved work to life.',
        'longitude' => 120.9796,
        'latitude' => 14.5565,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Filipino Indie Film Festival',
        'date' => '2025-08-05',
        'time' => '11:00AM - 11:00PM',
        'venue' => 'Glorietta Activity Center',
        'address' => 'Makati',
        'description' => 'Celebrating the vibrant independent cinema scene of the Philippines, this film festival showcases innovative storytelling from emerging and established Filipino filmmakers. The program features full-length features, short films, documentaries, and experimental works that explore diverse aspects of Filipino culture and contemporary issues. Q&A sessions with directors and actors provide insights into the creative process behind these compelling films.',
        'longitude' => 121.0264,
        'latitude' => 14.5531,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Wanderland Music & Arts Festival',
        'date' => '2025-05-08',
        'time' => '12:00PM - 12:00AM',
        'venue' => 'Filinvest City Event Grounds',
        'address' => 'Alabang',
        'description' => 'Wanderland returns with its signature blend of international and local music acts across multiple genres. This two-day festival creates an immersive experience with art installations, interactive activities, and food vendors curated to complement the musical lineup. Known for its relaxed atmosphere and community vibe, Wanderland has become a highlight of the Philippine festival calendar for music lovers seeking discovery and connection.',
        'longitude' => 121.0414,
        'latitude' => 14.4172,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Manila Auto Show 2025',
        'date' => '2025-09-05',
        'time' => '10:00AM - 9:00PM',
        'venue' => 'World Trade Center',
        'address' => 'Pasay',
        'description' => 'The Manila Auto Show presents the latest vehicles, automotive technology, and aftermarket products in the Philippines\' largest motoring event. Major manufacturers unveil new models and concept cars alongside custom builds from local garages and restoration specialists. With test drive opportunities, driving simulators, and technical workshops, this show appeals to automotive enthusiasts, industry professionals, and families looking for their next vehicle.',
        'longitude' => 120.9845,
        'latitude' => 14.5368,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Philippine Science Festival',
        'date' => '2025-07-10',
        'time' => '9:00AM - 6:00PM',
        'venue' => 'University of Santo Tomas',
        'address' => 'Manila',
        'description' => 'The Philippine Science Festival makes science accessible and exciting through interactive exhibits, demonstrations, and talks by leading researchers. Designed for curious minds of all ages, this event covers diverse scientific fields including astronomy, robotics, environmental science, and biotechnology. School groups, families, and science enthusiasts can participate in hands-on experiments and discover the wonders of scientific discovery in engaging ways.',
        'longitude' => 120.9873,
        'latitude' => 14.6099,
        'category' => 'KIDS'
    ],
    [
        'name' => 'Manila Fashion Week',
        'date' => '2025-08-15',
        'time' => 'Various Times',
        'venue' => 'Solaire Resort & Casino',
        'address' => 'Parañaque',
        'description' => 'Manila Fashion Week showcases the creativity and craftsmanship of Philippine designers alongside international fashion labels. Runway shows present collections ranging from haute couture to ready-to-wear, with special focus on sustainable fashion and traditional Filipino textiles. Industry panels, design exhibitions, and pop-up retail spaces make this a comprehensive celebration of style that highlights the Philippines\' position in the global fashion landscape.',
        'longitude' => 120.9798,
        'latitude' => 14.5203,
        'category' => 'ARTS'
    ],
    [
        'name' => 'BTS: Map of the Soul Tour',
        'date' => '2025-07-22',
        'time' => '6:30PM - 10:00PM',
        'venue' => 'Philippine Arena',
        'address' => 'Bulacan',
        'description' => 'Global phenomenon BTS brings their electrifying Map of the Soul Tour to Manila. The record-breaking K-pop group will perform their chart-topping hits with spectacular production, precision choreography, and the charismatic stage presence that has won them millions of fans worldwide. This highly anticipated concert promises an unforgettable experience for ARMY members and music fans alike.',
        'longitude' => 120.9481,
        'latitude' => 14.7631,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Philippine Independence Day Expo',
        'date' => '2025-06-12',
        'time' => '9:00AM - 6:00PM',
        'venue' => 'Manila Hotel',
        'address' => 'Manila',
        'description' => 'Commemorating Philippine Independence Day, this exhibition presents key moments in the nation\'s history through artifacts, documents, and interactive displays. From pre-colonial times through the Spanish and American periods to modern independence, the exhibits trace the evolution of Filipino identity and nationhood. Historians and cultural experts lead guided tours and discussions that bring the country\'s rich historical tapestry to life.',
        'longitude' => 120.9748,
        'latitude' => 14.5831,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Philippine Craft Beer Festival',
        'date' => '2025-05-17',
        'time' => '4:00PM - 12:00AM',
        'venue' => 'Circuit Makati',
        'address' => 'Makati',
        'description' => 'Celebrate the thriving local craft beer scene at this festival featuring over 30 Philippine microbreweries. Sample a diverse range of styles from hoppy IPAs to rich stouts, many incorporating unique local ingredients and flavors. Brewers share their expertise in tasting sessions, while food pairings, live music, and brewing demonstrations create a festive atmosphere for beer enthusiasts and curious newcomers alike.',
        'longitude' => 121.0153,
        'latitude' => 14.5652,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Cinemalaya Independent Film Festival',
        'date' => '2025-08-02',
        'time' => 'Various Times',
        'venue' => 'Cultural Center',
        'address' => 'Manila',
        'description' => 'Cinemalaya continues its mission of discovering and supporting fresh Filipino filmmaking talent with its annual showcase of independent cinema. Competition entries in short and feature-length categories present stories that push creative boundaries and reflect diverse perspectives on Philippine society. Retrospectives, tributes, and international selections round out the program for this essential event in the country\'s cultural calendar.',
        'longitude' => 120.9796,
        'latitude' => 14.5565,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Tech Summit Philippines',
        'date' => '2025-07-20',
        'time' => '9:00AM - 5:00PM',
        'venue' => 'The Podium',
        'address' => 'Ortigas',
        'description' => 'The Tech Summit brings together industry leaders, startups, developers, and tech enthusiasts to explore emerging technologies and digital innovation. Conference tracks cover artificial intelligence, fintech, e-commerce, cybersecurity, and the startup ecosystem, with keynote speeches and panel discussions from local and international experts. Networking opportunities, product demonstrations, and a startup pitch competition make this the premier event for the Philippine tech community.',
        'longitude' => 121.0626,
        'latitude' => 14.5858,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Summer Basketball Tournament',
        'date' => '2025-04-15',
        'time' => '4:00PM - 8:00PM',
        'venue' => 'Cuneta Astrodome',
        'address' => 'Pasay',
        'description' => 'The Summer Basketball Tournament sees the top college teams battle for championship glory. This tournament showcases the future stars of Philippine basketball in high-stakes games filled with skill, strategy, and school pride. With passionate fan bases creating an electric atmosphere, these games embody the competitive spirit and community connection that make collegiate sports a beloved national tradition.',
        'longitude' => 120.9947,
        'latitude' => 14.5391,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Summer Arts Festival',
        'date' => '2025-06-05',
        'time' => 'All Day',
        'venue' => 'Various Locations',
        'address' => 'Intramuros',
        'description' => 'The Summer Arts Festival transforms Intramuros into a vibrant celebration of Filipino creativity. Street performances, music competitions, art exhibitions, and cultural workshops fill the week-long event that showcases the talent and artistic vision of local creators. Elaborately designed installations and interactive exhibits create an immersive experience that draws visitors from across the Philippines and beyond.',
        'longitude' => 120.9748,
        'latitude' => 14.5890,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Career Fair 2025',
        'date' => '2025-06-30',
        'time' => '9:00AM - 5:00PM',
        'venue' => 'Ayala Malls Manila Bay',
        'address' => 'Parañaque',
        'description' => 'The Career Fair connects job seekers with opportunities across multiple industries, featuring recruitment booths from over 100 companies. Beyond job applications, the event offers career development workshops, resume reviews, mock interviews, and guidance on professional growth. Special sections focus on opportunities for fresh graduates, overseas workers, and specialized technical fields, creating pathways to meaningful employment.',
        'longitude' => 120.9900,
        'latitude' => 14.5179,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Ateneo vs La Salle: Basketball Rivalry',
        'date' => '2025-07-08',
        'time' => '4:00PM - 6:00PM',
        'venue' => 'Smart Araneta',
        'address' => 'Cubao',
        'description' => 'The legendary basketball rivalry between Ateneo and La Salle continues with another highly anticipated matchup. These games transcend sport to become cultural events that unite generations of alumni and highlight the unique traditions of both prestigious universities. With high-level basketball, spirited school bands, and coordinated cheering sections, this game promises to deliver the intensity and pageantry that have made it the premier rivalry in Philippine collegiate sports.',
        'longitude' => 121.0514,
        'latitude' => 14.6197,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Rainy Day Music Festival',
        'date' => '2025-08-15',
        'time' => '3:00PM - 10:00PM',
        'venue' => 'Greenfield District',
        'address' => 'Mandaluyong',
        'description' => 'The Rainy Day Music Festival brings together local indie artists for an intimate indoor music festival celebrating the rainy season. Featuring acoustic sets, folk music, and indie rock performances, this cozy event creates the perfect ambiance for the monsoon season. Warm food, hot drinks, and a marketplace of handcrafted items complete the experience that has become a beloved annual tradition for music lovers.',
        'longitude' => 121.0514,
        'latitude' => 14.5850,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Social Media Marketing Summit',
        'date' => '2025-09-25',
        'time' => '9:00AM - 5:00PM',
        'venue' => 'SMX Convention',
        'address' => 'Pasay',
        'description' => 'The Social Media Marketing Summit brings together digital marketing professionals, content creators, and brand strategists to explore the latest trends and best practices in social media marketing. Through keynote presentations, panel discussions, and hands-on workshops, attendees will gain practical insights on platform algorithms, content strategy, influencer partnerships, and measuring ROI. Network with industry leaders and discover innovative approaches to building authentic connections with audiences in the evolving digital landscape.',
        'longitude' => 120.9866,
        'latitude' => 14.5362,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Oktoberfest Manila',
        'date' => '2025-10-10',
        'time' => '4:00PM - 2:00AM',
        'venue' => 'BGC Amphitheater',
        'address' => 'Taguig',
        'description' => 'Oktoberfest Manila brings the iconic German beer festival to the Philippines with a local twist. Enjoy authentic German brews alongside Filipino craft beers in a festive atmosphere complete with traditional Bavarian music, games, and cuisine. Elaborate beer tents, live bands, and cultural performances create an immersive experience that celebrates both German traditions and Filipino hospitality. Special beer tasting sessions and brewing demonstrations add educational elements to this jubilant event.',
        'longitude' => 121.0500,
        'latitude' => 14.5478,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Photography Workshop Series',
        'date' => '2025-10-05',
        'time' => '1:00PM - 6:00PM',
        'venue' => 'De La Salle University',
        'address' => 'Manila',
        'description' => 'The Photography Workshop Series offers comprehensive training for photographers at all skill levels. Led by renowned professional photographers, these workshops cover everything from basic camera techniques to advanced composition, lighting, and post-processing. Specialized sessions focus on street photography, portraiture, landscape, and documentary styles. Participants will engage in hands-on shooting exercises, receive personalized feedback, and learn practical tips to elevate their photographic vision and technical abilities.',
        'longitude' => 120.9937,
        'latitude' => 14.5647,
        'category' => 'ARTS'
    ],
    [
        'name' => 'SEVENTEEN World Tour',
        'date' => '2025-10-18',
        'time' => '6:30PM - 10:00PM',
        'venue' => 'Mall Of Asia Arena',
        'address' => 'Pasay',
        'description' => 'K-pop powerhouse SEVENTEEN brings their electrifying world tour to Manila. Known for their synchronous choreography, powerful performances, and diverse musical styles, the 13-member group will showcase hits from their extensive discography. With spectacular stage design, stunning visual effects, and the group\'s signature high-energy performances, this concert will demonstrate why SEVENTEEN has become one of K-pop\'s most respected acts globally. CARATs can expect special fan engagement segments and memorable group and unit performances.',
        'longitude' => 120.9841,
        'latitude' => 14.5344,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Christmas Toy Convention',
        'date' => '2025-11-15',
        'time' => '10:00AM - 8:00PM',
        'venue' => 'Megamall Megatrade Hall',
        'address' => 'Mandaluyong',
        'description' => 'The Christmas Toy Convention is a paradise for collectors, enthusiasts, and families seeking unique gifts for the holiday season. This massive exhibition features rare collectibles, limited edition figures, vintage toys, and the latest releases from major toy manufacturers and independent creators. Meet toy designers, participate in trading sessions, and enjoy special displays of iconic toy lines through the decades. Interactive play areas, cosplay competitions, and toy-making workshops add to the festive atmosphere of this pre-holiday celebration.',
        'longitude' => 121.0574,
        'latitude' => 14.5843,
        'category' => 'KIDS'
    ],
    [
        'name' => 'Volleyball Nations League',
        'date' => '2025-09-18',
        'time' => '3:00PM - 9:00PM',
        'venue' => 'Mall Of Asia Arena',
        'address' => 'Pasay',
        'description' => 'The Volleyball Nations League brings world-class international volleyball to Manila as the Philippine team hosts powerful squads from volleyball powerhouse nations. This Olympic-level competition showcases the highest caliber of volleyball skill, with lightning-fast spikes, strategic plays, and amazing defensive efforts. Witness the Philippine team compete on home soil against some of the world\'s best volleyball athletes in this prestigious international tournament that has become a highlight of the global volleyball calendar.',
        'longitude' => 120.9841,
        'latitude' => 14.5344,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Manila International Film Festival',
        'date' => '2025-11-25',
        'time' => 'Various Times',
        'venue' => 'Various Venues',
        'address' => 'Metro Manila',
        'description' => 'The Manila International Film Festival presents outstanding cinema from around the world while showcasing the best of Filipino filmmaking. The curated program includes award-winning features, compelling documentaries, innovative short films, and special retrospectives of influential directors. Beyond screenings, the festival offers masterclasses with acclaimed filmmakers, industry panels on film production and distribution, and networking events that connect Filipino talent with international counterparts. This celebration of cinematic artistry attracts film lovers, critics, and industry professionals from across Southeast Asia and beyond.',
        'longitude' => 121.0000,
        'latitude' => 14.5800,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Comics and Collectibles Convention',
        'date' => '2025-10-25',
        'time' => '10:00AM - 8:00PM',
        'venue' => 'SMX Convention',
        'address' => 'Pasay',
        'description' => 'The Comics and Collectibles Convention is the ultimate gathering for comic book fans, collectors, and pop culture enthusiasts. Explore extensive exhibitor areas featuring rare comics, action figures, trading cards, and memorabilia from both international franchises and local artists. Special guests include renowned comic book creators, illustrators, and voice actors who participate in panel discussions, signing sessions, and live drawing demonstrations. Cosplay competitions, gaming tournaments, and exclusive merchandise releases make this a must-attend event for the geek community.',
        'longitude' => 120.9866,
        'latitude' => 14.5362,
        'category' => 'ARTS'
    ],
    [
        'name' => 'UAAP Cheerdance Competition',
        'date' => '2025-10-05',
        'time' => '2:00PM - 6:00PM',
        'venue' => 'Mall Of Asia Arena',
        'address' => 'Pasay',
        'description' => 'The UAAP Cheerdance Competition showcases the stunning athleticism, creativity, and school spirit of the top university cheerdance teams. Each squad delivers a meticulously choreographed routine combining acrobatic stunts, synchronized dance movements, and towering pyramids set to carefully selected music that represents their university\'s identity. This beloved tradition brings together thousands of alumni and students in a colorful display of university pride, with elaborate costumes and props enhancing the spectacular performances that push the boundaries of collegiate cheerdance.',
        'longitude' => 120.9841,
        'latitude' => 14.5344,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Christmas Symphony',
        'date' => '2025-12-15',
        'time' => '8:00PM - 10:00PM',
        'venue' => 'Manila Cathedral',
        'address' => 'Intramuros',
        'description' => 'The Christmas Symphony presents beloved holiday music performed by a full orchestra and choir in the magnificent acoustic setting of Manila Cathedral. The program features classical compositions like Handel\'s Messiah alongside traditional Filipino Christmas music and popular holiday favorites. The cathedral\'s historic architecture, enhanced by seasonal decorations and lighting, creates a magical atmosphere for this annual concert that has become a cherished tradition for many families. Special guest soloists add variety to this elegant celebration of the season\'s music.',
        'longitude' => 120.9752,
        'latitude' => 14.5892,
        'category' => 'ARTS'
    ],
    [
        'name' => 'New Year\'s Eve Countdown',
        'date' => '2025-12-31',
        'time' => '8:00PM - 1:00AM',
        'venue' => 'BGC Bonifacio High Street',
        'address' => 'Taguig',
        'description' => 'Ring in 2026 at BGC\'s spectacular New Year\'s Eve Countdown featuring multiple entertainment zones, food festivals, and an immersive light show throughout the High Street area. Live performances from top Filipino bands and DJs build energy throughout the evening, culminating in a synchronized multimedia countdown and breathtaking fireworks display at midnight. Family-friendly activities in designated areas ensure that revelers of all ages can participate in this joyous community celebration of new beginnings.',
        'longitude' => 121.0551,
        'latitude' => 14.5509,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Holiday Fun Fair',
        'date' => '2025-12-20',
        'time' => '10:00AM - 10:00PM',
        'venue' => 'Filinvest Tent',
        'address' => 'Alabang',
        'description' => 'The Holiday Fun Fair transforms Filinvest Tent into a winter wonderland of family entertainment featuring carnival rides, games, and seasonal activities. Children can visit Santa\'s workshop, participate in cookie decorating sessions, and enjoy holiday-themed puppet shows and magic performances. The indoor snow play area, complete with sledding hills and snowman-building stations, creates a unique experience rarely found in the Philippines. Festive food stalls and a holiday market with handcrafted gifts complete this magical year-end attraction.',
        'longitude' => 121.0446,
        'latitude' => 14.4237,
        'category' => 'KIDS'
    ],
    [
        'name' => 'Fringe Theater Festival',
        'date' => '2025-11-10',
        'time' => 'Various Times',
        'venue' => 'Various Venues',
        'address' => 'Poblacion, Makati',
        'description' => 'The Fringe Theater Festival showcases experimental, independent, and boundary-pushing theatrical productions across multiple venues in Poblacion. Productions range from intimate one-person shows to immersive theatrical experiences that transform unexpected spaces into performance venues. The festival provides a platform for emerging playwrights, directors, and performers to present unconventional works that challenge traditional theater formats. This celebration of creative risk-taking has become an important incubator for innovative theatrical voices in the Philippine performing arts scene.',
        'longitude' => 121.0385,
        'latitude' => 14.5652,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Marathon for a Cause',
        'date' => '2025-11-30',
        'time' => '4:00AM - 10:00AM',
        'venue' => 'SM Mall of Asia Complex',
        'address' => 'Pasay',
        'description' => 'The Marathon for a Cause combines athletic achievement with charitable impact, raising funds for education programs in underserved communities. Featuring 42K, 21K, 10K, and 5K race categories, the event welcomes both serious runners and casual participants supporting the cause. The scenic route along Manila Bay provides beautiful sunrise views, while entertainment stations and cheering squads maintain energy throughout the course. Post-race activities include a health and wellness expo, recovery stations, and a celebration of community service and athletic accomplishment.',
        'longitude' => 120.9800,
        'latitude' => 14.5347,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Sustainability Expo',
        'date' => '2025-11-05',
        'time' => '9:00AM - 6:00PM',
        'venue' => 'Ayala Triangle Gardens',
        'address' => 'Makati',
        'description' => 'The Sustainability Expo showcases innovative solutions for environmental challenges through interactive exhibits, demonstrations, and forums. Featuring organizations ranging from established corporations implementing green practices to startups developing cutting-edge sustainable technologies, the expo creates a space for learning and collaboration. Educational workshops offer practical sustainability tips for daily life, while panel discussions address larger issues like renewable energy, waste reduction, and climate action. This event connects environmentally conscious consumers with businesses and initiatives leading the way toward a more sustainable future.',
        'longitude' => 121.0244,
        'latitude' => 14.5582,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Craft Chocolate Fair',
        'date' => '2025-10-15',
        'time' => '10:00AM - 8:00PM',
        'venue' => 'Power Plant Mall',
        'address' => 'Rockwell, Makati',
        'description' => 'The Craft Chocolate Fair celebrates the growing artisanal chocolate movement in the Philippines, highlighting local cacao producers and chocolate makers who are gaining international recognition. Visitors can sample bean-to-bar chocolates that showcase the unique flavor profiles of Philippine cacao from different regions. Educational workshops cover chocolate tasting techniques, the chocolate-making process, and the important role of sustainable cacao farming. Culinary demonstrations by renowned pastry chefs feature innovative uses of local chocolate in both traditional and contemporary desserts.',
        'longitude' => 121.0392,
        'latitude' => 14.5654,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Dragon Boat Festival',
        'date' => '2025-10-12',
        'time' => '7:00AM - 4:00PM',
        'venue' => 'Manila Bay',
        'address' => 'Roxas Boulevard, Manila',
        'description' => 'The Dragon Boat Festival brings together teams from across the Philippines and international competitors for a day of intense racing in colorfully decorated dragon boats. This ancient tradition combines athletic prowess, teamwork, and cultural celebration as drums beat to synchronize the paddlers\' powerful strokes. Spectators line the bay to cheer for their favorite teams while enjoying cultural performances, food festivals, and water sports demonstrations between races. The event highlights the growing popularity of this dynamic water sport while honoring its rich cultural heritage.',
        'longitude' => 120.9741,
        'latitude' => 14.5762,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Future Education Forum',
        'date' => '2025-09-30',
        'time' => '9:00AM - 5:00PM',
        'venue' => 'Ateneo de Manila University',
        'address' => 'Quezon City',
        'description' => 'The Future Education Forum brings together educators, technology innovators, policy makers, and students to explore emerging approaches to learning in the digital age. Conference tracks address topics such as AI in education, personalized learning systems, developing critical thinking skills, and creating more inclusive educational environments. Interactive demonstrations showcase cutting-edge educational technologies while collaborative workshops encourage participants to reimagine traditional educational models. This forward-looking event helps prepare educational institutions and professionals for the rapidly evolving landscape of 21st century learning.',
        'longitude' => 121.0782,
        'latitude' => 14.6402,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Indoor Climbing Competition',
        'date' => '2025-09-28',
        'time' => '9:00AM - 7:00PM',
        'venue' => 'Climb Central Manila',
        'address' => 'Mandaluyong',
        'description' => 'The Indoor Climbing Competition challenges climbers of all levels to test their skills on professionally set routes of varying difficulty. Categories include boulder problems, speed climbing, and lead climbing with divisions for youth, recreational adult, and elite competitive climbers. Spectators can appreciate the combination of physical strength, problem-solving, and mental focus required as climbers navigate complex routes on the colorful walls. Climbing workshops, equipment demonstrations, and opportunities to try the sport make this an engaging event for both the climbing community and curious newcomers.',
        'longitude' => 121.0564,
        'latitude' => 14.5785,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Pinoy Pop Convention',
        'date' => '2025-12-05',
        'time' => '10:00AM - 9:00PM',
        'venue' => 'World Trade Center',
        'address' => 'Pasay',
        'description' => 'The Pinoy Pop Convention celebrates the vibrant world of P-pop (Philippine Pop) with performances, fan meets, and interactive exhibitions featuring the country\'s top idol groups. This gathering connects fans with their favorite artists through autograph sessions, photo opportunities, and exclusive merchandise. Industry panels discuss the growth of the P-pop movement and its increasing global recognition, while aspiring performers can participate in audition workshops and dance cover competitions. This event highlights how Filipino artists are creating their own unique space in the global pop music landscape.',
        'longitude' => 120.9845,
        'latitude' => 14.5368,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Christmas Lights Festival',
        'date' => '2025-12-01',
        'time' => '6:00PM - 11:00PM',
        'venue' => 'Ayala Avenue',
        'address' => 'Makati',
        'description' => 'The Ayala Avenue Christmas Lights Festival transforms the city\'s business district into a magical holiday wonderland with spectacular light displays, 3D projections, and musical light shows synchronized to beloved Christmas music. The month-long celebration features weekend performances by choirs, orchestras, and dance troupes that bring holiday cheer to thousands of nightly visitors. This Filipino Christmas tradition has become one of the most photographed holiday events in Metro Manila, creating magical memories for families and capturing the joyous spirit of the season through art, light, and music.',
        'longitude' => 121.0227,
        'latitude' => 14.5547,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Year-End Jazz Festival',
        'date' => '2025-12-27',
        'time' => '5:00PM - 11:00PM',
        'venue' => 'Greenbelt Park',
        'address' => 'Makati',
        'description' => 'The Year-End Jazz Festival brings together acclaimed jazz musicians from the Philippines and around the world for an elegant evening under the stars. Set in the lush Greenbelt Park, the festival features multiple stages showcasing different jazz styles from traditional and Latin to fusion and contemporary. Gourmet food stations and fine wine pairings complement the sophisticated musical experience. Intimate seating arrangements and excellent acoustics create the perfect atmosphere to appreciate the improvisational brilliance and technical mastery of the featured performers.',
        'longitude' => 121.0225,
        'latitude' => 14.5512,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'International Volleyball Championships',
        'date' => '2026-01-15',
        'time' => '2:00PM - 8:00PM',
        'venue' => 'PhilSports Arena',
        'address' => 'Pasig',
        'description' => 'The International Volleyball Championships brings elite teams from across Asia and beyond to compete in this prestigious tournament. Featuring fast-paced action, strategic play, and exceptional athleticism, these matches showcase volleyball at its highest level. The Philippine national team will face challenging opponents as they represent the country on home soil. Special exhibition games and volleyball clinics with international stars provide development opportunities for young players while building excitement for this globally popular sport.',
        'longitude' => 121.0815,
        'latitude' => 14.5865,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Philippine Dance Festival',
        'date' => '2026-01-25',
        'time' => '3:00PM - 9:00PM',
        'venue' => 'SM Aura Premier',
        'address' => 'Taguig',
        'description' => 'The Philippine Dance Festival celebrates the diversity of dance traditions from across the archipelago alongside contemporary dance innovations. Performance showcases feature everything from indigenous ritual dances to ballet, modern dance, street dance, and ballroom competitions. Workshop sessions allow participants to learn dance styles from master instructors, while symposiums explore the cultural and historical significance of dance in Filipino society. This immersive event honors dance as both an expression of cultural heritage and a dynamic, evolving art form.',
        'longitude' => 121.0541,
        'latitude' => 14.5473,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Filipino Heritage Celebration',
        'date' => '2026-02-05',
        'time' => '9:00AM - 9:00PM',
        'venue' => 'Intramuros',
        'address' => 'Manila',
        'description' => 'The Filipino Heritage Celebration transforms the historic walled city of Intramuros into an immersive journey through the Philippines\' rich cultural history. Interactive exhibits, traditional craft demonstrations, and historical reenactments bring the nation\'s past to life. Culinary pavilions offer regional specialties from across the archipelago, while cultural performances showcase musical and dance traditions from different provinces. Educational tours, led by historians and cultural experts, provide deeper insights into the architectural and historical significance of this landmark district.',
        'longitude' => 120.9748,
        'latitude' => 14.5890,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Children\'s Literature Festival',
        'date' => '2026-01-30',
        'time' => '9:00AM - 5:00PM',
        'venue' => 'Museo Pambata',
        'address' => 'Manila',
        'description' => 'The Children\'s Literature Festival celebrates the magic of storytelling with a focus on Filipino children\'s books and their creators. Young readers can meet beloved authors and illustrators, participate in interactive storytelling sessions, and enjoy puppet shows and dramatic adaptations of popular stories. Writing and illustration workshops encourage creative expression, while panel discussions for parents and educators explore the importance of cultivating a love of reading from an early age. The festival showcases both established classics and emerging voices in Philippine children\'s literature.',
        'longitude' => 120.9798,
        'latitude' => 14.5877,
        'category' => 'KIDS'
    ],
    [
        'name' => 'Sinulog Festival 2026',
        'date' => '2026-01-18',
        'time' => 'All Day',
        'venue' => 'Manila Branch',
        'address' => 'Manila',
        'description' => 'Experience the vibrant Sinulog Festival, celebrating the Filipino people\'s acceptance of Christianity and devotion to the Santo Niño. This Manila satellite celebration of Cebu\'s famous festival features colorful street dancing, rhythmic drumbeats, and the distinctive "two steps forward, one step back" movement that mimics the current of the river (sinulog). Participants in elaborate costumes perform choreographed routines while carrying images of the Santo Niño. Cultural presentations, a solemn procession, and a high-energy grand parade make this one of the most spectacular cultural events of the year.',
        'longitude' => 120.9850,
        'latitude' => 14.5800,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Urban Art Exhibition',
        'date' => '2026-02-15',
        'time' => '11:00AM - 9:00PM',
        'venue' => 'The Alley at Karrivin',
        'address' => 'Makati',
        'description' => 'The Urban Art Exhibition showcases the vibrant street art scene of the Philippines, bringing together graffiti artists, muralists, and urban contemporary artists in a gallery setting. Large-scale installations, live painting demonstrations, and a curated collection of works explore themes of city life, social commentary, and cultural identity. The exhibition documents how Filipino urban artists have developed distinctive styles that blend international influences with local context and aesthetics. Panel discussions examine the evolution of street art from underground expression to recognized art form.',
        'longitude' => 121.0138,
        'latitude' => 14.5638,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Chinese New Year Festival',
        'date' => '2026-02-10',
        'time' => '10:00AM - 10:00PM',
        'venue' => 'Binondo',
        'address' => 'Manila',
        'description' => 'The Chinese New Year Festival transforms the world\'s oldest Chinatown into a magnificent celebration of Filipino-Chinese culture and traditions. The festivities begin with a vibrant parade featuring dragon and lion dancers, cultural performances, and elaborate floats. Food stalls line the streets offering traditional delicacies, while temples and heritage buildings open their doors for special tours and cultural activities. As night falls, a spectacular fireworks display illuminates the sky, symbolizing good fortune and prosperity for the coming year.',
        'longitude' => 120.9747,
        'latitude' => 14.5986,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Tech Startup Conference',
        'date' => '2026-02-20',
        'time' => '9:00AM - 6:00PM',
        'venue' => 'SMX Convention',
        'address' => 'Pasay',
        'description' => 'The Tech Startup Conference brings together entrepreneurs, investors, and industry leaders to explore the dynamic startup ecosystem in the Philippines. Keynote speeches from successful founders share insights on building scalable businesses, while panel discussions address fundraising strategies, regulatory challenges, and emerging technology trends. The startup showcase allows promising ventures to present their innovations to potential investors and partners. Specialized tracks cover fintech, e-commerce, health tech, and sustainable solutions, highlighting how Filipino startups are tackling local and global challenges through technology.',
        'longitude' => 120.9866,
        'latitude' => 14.5362,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Esports National Championship',
        'date' => '2026-03-05',
        'time' => '10:00AM - 10:00PM',
        'venue' => 'SM Mall of Asia Arena',
        'address' => 'Pasay',
        'description' => 'The Esports National Championship showcases the Philippines\' top gaming talent competing across multiple popular titles including Mobile Legends, DOTA 2, Valorant, and more. This premium esports event features professional teams battling for substantial prize pools and national recognition in custom-built competition areas with state-of-the-art gaming setups. Giant screens display the action for thousands of spectators, while commentators provide analysis of the strategic gameplay. The fan experience includes meet-and-greets with gaming celebrities, casual gaming zones, and exclusive merchandise from leading gaming brands.',
        'longitude' => 120.9841,
        'latitude' => 14.5344,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Philippine Architecture and Design Expo',
        'date' => '2026-03-15',
        'time' => '10:00AM - 7:00PM',
        'venue' => 'World Trade Center',
        'address' => 'Pasay',
        'description' => 'The Philippine Architecture and Design Expo showcases innovative concepts in tropical architecture, sustainable building practices, and contemporary Filipino design. Industry professionals present cutting-edge projects that respond to environmental challenges while honoring cultural contexts and traditions. Exhibition zones feature sustainable building materials, smart home technologies, and furniture designs that highlight Filipino craftsmanship and creativity. Architectural tours of significant Manila buildings complement the expo experience, while design competitions encourage fresh thinking about urban living spaces for the Philippine context.',
        'longitude' => 120.9845,
        'latitude' => 14.5368,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Wellness and Yoga Festival',
        'date' => '2026-03-20',
        'time' => '7:00AM - 7:00PM',
        'venue' => 'Bonifacio High Street Amphitheater',
        'address' => 'Taguig',
        'description' => 'The Wellness and Yoga Festival creates a day-long retreat experience in the heart of the city, featuring yoga sessions for all levels, meditation workshops, and mindfulness practices led by renowned instructors. Wellness pavilions offer holistic health services, nutritional guidance, and natural products that support balanced living. Discussion forums address topics such as stress management, work-life harmony, and the integration of traditional healing practices with modern wellness approaches. This rejuvenating event encourages participants to prioritize self-care and develop sustainable wellness routines.',
        'longitude' => 121.0551,
        'latitude' => 14.5509,
        'category' => 'ARTS'
    ],
    [
        'name' => 'ENHYPEN FATE World Tour',
        'date' => '2026-03-28',
        'time' => '6:30PM - 9:30PM',
        'venue' => 'Philippine Arena',
        'address' => 'Bulacan',
        'description' => 'ENHYPEN brings their spectacular FATE World Tour to the Philippines, performing for thousands of ENGENE fans in the country\'s largest indoor arena. The phenomenally popular K-pop boy group will showcase their impressive discography with state-of-the-art production, intricate choreography, and special stages designed exclusively for this tour. Known for their synchronized performances and distinctive music that blends various genres, ENHYPEN delivers an unforgettable concert experience that highlights both their group synergy and individual talents across vocal and dance performances.',
        'longitude' => 120.9481,
        'latitude' => 14.7631,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Science and Discovery Fair',
        'date' => '2026-04-05',
        'time' => '9:00AM - 6:00PM',
        'venue' => 'The Mind Museum',
        'address' => 'Taguig',
        'description' => 'The Science and Discovery Fair transforms The Mind Museum and its surroundings into an interactive celebration of scientific exploration for curious minds of all ages. Engaging exhibits demonstrate scientific principles through hands-on experiments, while robotics demonstrations, chemistry shows, and physics presentations make complex concepts accessible and exciting. Young inventors can participate in design challenges and present their own creative solutions to real-world problems. Special activities focus on environmental science, promoting awareness of conservation issues and inspiring future stewards of the Philippines\' natural resources.',
        'longitude' => 121.0453,
        'latitude' => 14.5488,
        'category' => 'KIDS'
    ],
    [
        'name' => 'Hotdog Music Tribute Festival',
        'date' => '2026-04-10',
        'time' => '5:00PM - 12:00AM',
        'venue' => 'Music Museum',
        'address' => 'San Juan',
        'description' => 'The Hotdog Music Tribute Festival celebrates the legendary Filipino band that pioneered Manila Sound in the 1970s, blending Western pop music with Filipino sensibilities. Contemporary artists reinterpret Hotdog\'s beloved classics like "Manila" and "Bongga Ka Day" alongside original band members, honoring their significant contribution to OPM (Original Pilipino Music). This nostalgic musical journey includes historical exhibits documenting the band\'s impact on Philippine popular culture and the evolution of Filipino music. Special collaborative performances highlight how Hotdog\'s innovative approach continues to influence today\'s musicians.',
        'longitude' => 121.0409,
        'latitude' => 14.5999,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'IVE First World Tour',
        'date' => '2026-04-15',
        'time' => '7:00PM - 10:00PM',
        'venue' => 'Mall Of Asia Arena',
        'address' => 'Pasay',
        'description' => 'K-pop sensation IVE brings their highly anticipated First World Tour to Manila, showcasing their chart-topping hits and captivating performances. Known for their sophisticated concept, powerful choreography, and distinctive music style, the group has rapidly risen to become one of K-pop\'s most successful acts. DIVEs (IVE\'s fandom) can expect spectacular stage production, stunning visuals, and special segments designed to create memorable interactions between the members and their fans. This concert promises to deliver the polished performance and charismatic stage presence that has earned the group international acclaim.',
        'longitude' => 120.9841,
        'latitude' => 14.5344,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Philippine Football League Finals',
        'date' => '2026-04-25',
        'time' => '7:00PM - 9:00PM',
        'venue' => 'Rizal Memorial Stadium',
        'address' => 'Manila',
        'description' => 'The Philippine Football League Finals brings together the country\'s top two football clubs for the championship match of the season. After months of competition, these elite teams battle for national supremacy in front of passionate supporters in the historic Rizal Memorial Stadium. Pre-game festivities include youth exhibition matches and football skills competitions, while halftime features special performances celebrating Philippine football culture. This premier sporting event showcases the growing quality and popularity of professional football in the Philippines while inspiring the next generation of Filipino football talent.',
        'longitude' => 120.9941,
        'latitude' => 14.5624,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'Mountain Bike Championship',
        'date' => '2026-05-02',
        'time' => '6:00AM - 5:00PM',
        'venue' => 'La Mesa Nature Reserve',
        'address' => 'Quezon City',
        'description' => 'The Mountain Bike Championship challenges riders with technical trails through the beautiful La Mesa Nature Reserve, featuring diverse race categories from cross-country and downhill to enduro and marathon distances. Amateur and professional divisions welcome riders of all skill levels to test themselves on courses designed to showcase both technical skills and endurance. Spectator zones at key technical features allow fans to witness the most exciting moments of each race, while a festival area offers bike demonstrations, maintenance workshops, and the latest equipment from leading cycling brands.',
        'longitude' => 121.0865,
        'latitude' => 14.7213,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'OPM Songwriters Festival',
        'date' => '2026-05-08',
        'time' => '4:00PM - 11:00PM',
        'venue' => '19 East',
        'address' => 'Paranaque',
        'description' => 'The OPM Songwriters Festival celebrates the creative minds behind the Philippines\' most beloved songs. This intimate event features accomplished composers performing their own works and sharing the stories behind their creation. Rising songwriters also showcase new material in a supportive environment that nurtures the next generation of Filipino musical storytellers. Collaborative performances and songwriting workshops create a vibrant exchange of ideas between established and emerging artists. This festival highlights the poetry, social commentary, and emotional depth that characterize the best of Original Pilipino Music across generations.',
        'longitude' => 121.0226,
        'latitude' => 14.4849,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Culinary Masters Exhibition',
        'date' => '2026-05-15',
        'time' => '11:00AM - 9:00PM',
        'venue' => 'Rockwell Tent',
        'address' => 'Makati',
        'description' => 'The Culinary Masters Exhibition brings together the Philippines\' most innovative chefs for a gastronomic showcase celebrating the country\'s evolving food scene. Interactive cooking demonstrations reveal the techniques behind signature dishes, while tasting pavilions offer opportunities to sample creations ranging from reinvented Filipino classics to cutting-edge fusion cuisine. Special features include a heritage food section highlighting regional cooking traditions, sustainable seafood presentations, and explorations of indigenous ingredients being rediscovered by contemporary chefs. This delicious event provides a comprehensive view of Philippine cuisine\'s rich history and exciting future.',
        'longitude' => 121.0387,
        'latitude' => 14.5640,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Animation and Comics Expo',
        'date' => '2026-05-25',
        'time' => '10:00AM - 8:00PM',
        'venue' => 'SMX Convention',
        'address' => 'Pasay',
        'description' => 'The Animation and Comics Expo showcases the thriving Filipino animation and comics industry, featuring exhibitions from major studios, independent creators, and educational institutions. Artist galleries display original artwork and comics, while industry panels discuss techniques, career opportunities, and the growing global recognition of Filipino talent in these fields. Animation screenings present both professional productions and outstanding student work, highlighting the diversity of styles and stories being created locally. Workshops covering traditional and digital techniques offer practical skills development for aspiring artists of all ages.',
        'longitude' => 120.9866,
        'latitude' => 14.5362,
        'category' => 'ARTS'
    ],
    [
        'name' => 'NewJeans Live in Manila',
        'date' => '2026-06-01',
        'time' => '7:00PM - 10:00PM',
        'venue' => 'Mall Of Asia Arena',
        'address' => 'Pasay',
        'description' => 'NewJeans brings their refreshing take on K-pop to Manila in their first major concert in the Philippines. Known for their distinctive Y2K-inspired aesthetics, captivating choreography, and uniquely nostalgic yet modern sound, the group has quickly established themselves as one of K-pop\'s most influential acts. Bunnies (NewJeans\' fandom) can expect performances of their hit songs delivered with the group\'s signature synchronized choreography and sweet vocal harmonies. The concert production emphasizes the members\' natural charm and musical talents through thoughtfully designed stages that complement their authentic performance style.',
        'longitude' => 120.9841,
        'latitude' => 14.5344,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Philippine Documentary Film Festival',
        'date' => '2026-06-10',
        'time' => 'Various Times',
        'venue' => 'UP Film Center',
        'address' => 'Quezon City',
        'description' => 'The Philippine Documentary Film Festival presents powerful non-fiction storytelling that explores the social, cultural, and environmental realities of contemporary Philippines. Screenings feature works from both established documentarians and emerging filmmakers who bring attention to untold stories across the archipelago. Director Q&A sessions and panel discussions create meaningful dialogue around the issues presented in the films, while masterclasses offer insights into documentary techniques and ethical considerations. This thought-provoking festival demonstrates how documentary film serves as both an artistic medium and a vital tool for social awareness and change.',
        'longitude' => 121.0642,
        'latitude' => 14.6565,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Science Fiction and Fantasy Convention',
        'date' => '2026-06-15',
        'time' => '10:00AM - 10:00PM',
        'venue' => 'SMX Convention',
        'address' => 'Pasay',
        'description' => 'The Science Fiction and Fantasy Convention creates an immersive experience for fans of speculative fiction across literature, film, gaming, and art. Special guests include international and local authors, artists, and performers who have contributed to these beloved genres. Panel discussions explore world-building techniques, the influence of Filipino mythology on contemporary fantasy, and the social commentary embedded in science fiction narratives. Elaborate cosplay competitions, tabletop gaming areas, and themed photo zones encourage active participation, while a marketplace offers exclusive merchandise, rare collectibles, and independently published works.',
        'longitude' => 120.9866,
        'latitude' => 14.5362,
        'category' => 'ARTS'
    ],
    [
        'name' => 'Beach Volleyball Tournament',
        'date' => '2026-06-20',
        'time' => '8:00AM - 6:00PM',
        'venue' => 'Vermosa Sports Hub',
        'address' => 'Cavite',
        'description' => 'The Beach Volleyball Tournament transforms Vermosa Sports Hub\'s sand courts into a competitive arena featuring the country\'s top beach volleyball athletes. Teams compete in men\'s, women\'s, and mixed divisions through pool play and elimination rounds, showcasing the impressive athleticism and strategy unique to the beach version of the sport. Between matches, visitors can participate in serving contests, skills clinics with professional players, and recreational games on practice courts. The festive atmosphere includes food concessions, live music, and vendor booths offering the latest in beach sports equipment and apparel.',
        'longitude' => 120.9346,
        'latitude' => 14.3229,
        'category' => 'SPORTS'
    ],
    [
        'name' => 'SB19 Homecoming Concert',
        'date' => '2026-07-01',
        'time' => '7:30PM - 10:30PM',
        'venue' => 'Smart Araneta Coliseum',
        'address' => 'Quezon City',
        'description' => 'P-pop pioneers SB19 return to the iconic Smart Araneta Coliseum for a spectacular homecoming concert celebrating their journey as the Philippines\' breakthrough global act. A\'TIN (SB19\'s fandom) will experience the group\'s powerful vocals, precise choreography, and charismatic stage presence through performances spanning their entire discography. This concert highlights SB19\'s unique blend of K-pop training methods with distinctly Filipino music sensibilities that has earned them international recognition while remaining deeply connected to their roots. Special segments showcase individual member talents and previously unreleased material from their latest creative projects.',
        'longitude' => 121.0514,
        'latitude' => 14.6197,
        'category' => 'CONCERT'
    ],
    [
        'name' => 'Philippine Contemporary Art Fair',
        'date' => '2026-07-10',
        'time' => '11:00AM - 9:00PM',
        'venue' => 'The Link Carpark',
        'address' => 'Makati',
        'description' => 'The Philippine Contemporary Art Fair transforms multiple levels of The Link Carpark into sophisticated gallery spaces showcasing the most exciting developments in Filipino visual arts. Leading galleries present carefully curated booths featuring established artists alongside emerging talents, offering collectors and enthusiasts a comprehensive view of the current art landscape. Special exhibitions highlight new media installations, performance art, and large-scale works created specifically for the fair. Guided tours, artist talks, and panel discussions provide context and deeper understanding of contemporary artistic practices in the Philippines and their place in the global art conversation.',
        'longitude' => 121.0264,
        'latitude' => 14.5506,
        'category' => 'ARTS'
    ],
];